name: Deploy app to AWS

on:
  push:
    branches:
      - development
      - stage
      - master

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    environment: production

    needs:
      - terraform
      - build

    steps:
      - run: echo ${{ needs.terraform.outputs.cinema-app-distribution_id }} ${{ needs.terraform.outputs.cinema-app-distribution_domain_name }}

      - name: Download build folder
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ~/

      - name: Deploy to s3
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: aws --region $AWS_DEFAULT_REGION s3 sync ~/build s3://$(echo ${{ needs.terraform.outputs.cinema_app_bucket_name }} | tr -d '"' ) --delete
