name: Build & deploy app

on:
  push:
    branches:
      - development
      - stage
      - master

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build:
    uses: ./.github/workflows/build.yml
    secrets:
      REACT_APP_MOVIE_API_KEY: ${{ secrets.REACT_APP_MOVIE_API_KEY }}

  deploy-aws:
    needs:
      - terraform
      - build
    uses: ./.github/workflows/deploy_aws.yml
    with:
      cinema_app_bucket_name: $(echo ${{ needs.terraform.outputs.cinema_app_bucket_name }} | tr -d '"' )
      cinema-app-distribution_id: $(echo ${{ needs.terraform.outputs.cinema-app-distribution_id }} | tr -d '"' )
    secrets:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-docker:
    needs:
      - build
    uses: ./.github/workflows/deploy_docker.yml
    secrets:
      REACT_APP_MOVIE_API_KEY: ${{ secrets.REACT_APP_MOVIE_API_KEY }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

  notify:
    needs:
      - deploy-docker
      - deploy-aws
    uses: ./.github/workflows/notify.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
