name: 'Terraform'

on:
  push:
    branches:
      - development
      - stage
      - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure

    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init & validate
        run: |
          terraform init
          terraform validate
          terraform fmt -check
        env:
          TF_WORKSPACE: ${{ env.BRANCH_NAME }}

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_WORKSPACE: ${{ env.BRANCH_NAME }}

      - name: Terraform Apply
        id: validate
        #  if: github.ref == 'refs/heads/development' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve
          mkdir -p outputs
          terraform output cinema_app_bucket_name > outputs/cinema_bucket_name.txt
          terraform output cinema-app-distribution_id > outputs/cinema-app-distribution_id.txt
          terraform output cinema-app-distribution_domain_name > outputs/cinema-app-distribution_domain_name.txt
        env:
          TF_WORKSPACE: ${{ env.BRANCH_NAME }}

      - run: echo $(terraform output test)
